# Generated by Django 5.2.4 on 2026-09-24 14:38

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMarketRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('CHENNAI', 'Chennai'), ('BANGALORE', 'Bangalore')], default='CHENNAI', max_length=20)),
                ('gold_24k_per_gram', models.DecimalField(decimal_places=2, default=Decimal('7480.00'), help_text='₹/gram 24K (999 pure)', max_digits=10)),
                ('gold_22k_per_gram', models.DecimalField(decimal_places=2, default=Decimal('6860.00'), help_text='₹/gram 22K (916 hallmark)', max_digits=10)),
                ('gold_18k_per_gram', models.DecimalField(decimal_places=2, default=Decimal('5610.00'), help_text='₹/gram 18K (750 hallmark)', max_digits=10)),
                ('silver_per_gram', models.DecimalField(decimal_places=2, default=Decimal('94.50'), help_text='₹/gram fine silver', max_digits=8)),
                ('silver_per_kg', models.DecimalField(decimal_places=2, default=Decimal('94500.00'), help_text='₹/kg bar silver', max_digits=10)),
                ('rate_date', models.DateField(default=datetime.date.today)),
                ('is_live', models.BooleanField(default=True)),
                ('source', models.CharField(default='IBJA / Bullion Direct Spot', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Market Rate',
                'verbose_name_plural': 'Daily Market Rates',
                'ordering': ['city', '-rate_date', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workshopsettings',
            name='name',
            field=models.CharField(default='GSCMS', max_length=150),
        ),
        migrations.AlterField(
            model_name='workshopsettings',
            name='tagline',
            field=models.CharField(blank=True, default='Jewellery & Goldsmith Workshop Management System', max_length=255),
        ),
    ]
