# Generated by Django 5.2.4 on 2026-09-24 15:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_dailymarketrate_customer_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymarketrate',
            name='change_24k_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Daily price change in ₹', max_digits=8),
        ),
        migrations.AddField(
            model_name='dailymarketrate',
            name='change_24k_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.33'), help_text='Daily price change in %', max_digits=5),
        ),
        migrations.AddField(
            model_name='dailymarketrate',
            name='change_direction',
            field=models.CharField(default='UP', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='atelier_stage',
            field=models.CharField(default='RECEIVED', max_length=40),
        ),
        migrations.AddField(
            model_name='job',
            name='custom_type_name',
            field=models.CharField(blank=True, help_text='Custom jewellery item name if Other', max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='polisher_given_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='polisher_received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stone_given_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stone_received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
